[project]
name = "diy-door-fan"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "cadquery>=2.5.2",
    "cq-editor>=0.5.0",
]
